blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/monkoose/neocodeium/discussions/new?category=q-a
    about: Ask questions about configuration and usage of NeoCodeium
